apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rate-limiter.fullname" . }}-config
  labels:
    {{- include "rate-limiter.labels" . | nindent 4 }}
data:
  rules.yaml: |
    server:
      grpc_addr: ":9090"
      http_addr: ":8080"
    redis:
      addr: {{ .Values.redis.addr | quote }}
      password: {{ .Values.redis.password | quote }}
      db: {{ .Values.redis.db }}
    rules:
      {{- range .Values.rules }}
      - name: {{ .name | quote }}
        limit: {{ .limit }}
        window: {{ .window | quote }}
      {{- end }}
